/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as CareerOpportunitiesRouteImport } from './routes/career-opportunities'
import { Route as ConsultancyValuationRouteImport } from './routes/consultancy-valuation'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as LettingServicesRouteImport } from './routes/letting-services'
import { Route as OurClientsRouteImport } from './routes/our-clients'
import { Route as OurPhotoGalleryRouteImport } from './routes/our-photo-gallery'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PropertyManagementRouteImport } from './routes/property-management'
import { Route as PropertySalesRouteImport } from './routes/property-sales'
import { Route as RentCollectionRouteImport } from './routes/rent-collection'
import { Route as Service4RouteImport } from './routes/service-4'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerOpportunitiesRoute = CareerOpportunitiesRouteImport.update({
  id: '/career-opportunities',
  path: '/career-opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultancyValuationRoute = ConsultancyValuationRouteImport.update({
  id: '/consultancy-valuation',
  path: '/consultancy-valuation',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const LettingServicesRoute = LettingServicesRouteImport.update({
  id: '/letting-services',
  path: '/letting-services',
  getParentRoute: () => rootRouteImport,
} as any)
const OurClientsRoute = OurClientsRouteImport.update({
  id: '/our-clients',
  path: '/our-clients',
  getParentRoute: () => rootRouteImport,
} as any)
const OurPhotoGalleryRoute = OurPhotoGalleryRouteImport.update({
  id: '/our-photo-gallery',
  path: '/our-photo-gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertyManagementRoute = PropertyManagementRouteImport.update({
  id: '/property-management',
  path: '/property-management',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertySalesRoute = PropertySalesRouteImport.update({
  id: '/property-sales',
  path: '/property-sales',
  getParentRoute: () => rootRouteImport,
} as any)
const RentCollectionRoute = RentCollectionRouteImport.update({
  id: '/rent-collection',
  path: '/rent-collection',
  getParentRoute: () => rootRouteImport,
} as any)
const Service4Route = Service4RouteImport.update({
  id: '/service-4',
  path: '/service-4',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/career-opportunities': typeof CareerOpportunitiesRoute
  '/consultancy-valuation': typeof ConsultancyValuationRoute
  '/contact': typeof ContactRoute
  '/letting-services': typeof LettingServicesRoute
  '/our-clients': typeof OurClientsRoute
  '/our-photo-gallery': typeof OurPhotoGalleryRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/property-management': typeof PropertyManagementRoute
  '/property-sales': typeof PropertySalesRoute
  '/rent-collection': typeof RentCollectionRoute
  '/service-4': typeof Service4Route
  '/services': typeof ServicesRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/career-opportunities': typeof CareerOpportunitiesRoute
  '/consultancy-valuation': typeof ConsultancyValuationRoute
  '/contact': typeof ContactRoute
  '/letting-services': typeof LettingServicesRoute
  '/our-clients': typeof OurClientsRoute
  '/our-photo-gallery': typeof OurPhotoGalleryRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/property-management': typeof PropertyManagementRoute
  '/property-sales': typeof PropertySalesRoute
  '/rent-collection': typeof RentCollectionRoute
  '/service-4': typeof Service4Route
  '/services': typeof ServicesRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/career-opportunities': typeof CareerOpportunitiesRoute
  '/consultancy-valuation': typeof ConsultancyValuationRoute
  '/contact': typeof ContactRoute
  '/letting-services': typeof LettingServicesRoute
  '/our-clients': typeof OurClientsRoute
  '/our-photo-gallery': typeof OurPhotoGalleryRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/property-management': typeof PropertyManagementRoute
  '/property-sales': typeof PropertySalesRoute
  '/rent-collection': typeof RentCollectionRoute
  '/service-4': typeof Service4Route
  '/services': typeof ServicesRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/career-opportunities'
    | '/consultancy-valuation'
    | '/contact'
    | '/letting-services'
    | '/our-clients'
    | '/our-photo-gallery'
    | '/privacy-policy'
    | '/property-management'
    | '/property-sales'
    | '/rent-collection'
    | '/service-4'
    | '/services'
    | '/terms-of-service'
    | '/blog/$slug'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/career-opportunities'
    | '/consultancy-valuation'
    | '/contact'
    | '/letting-services'
    | '/our-clients'
    | '/our-photo-gallery'
    | '/privacy-policy'
    | '/property-management'
    | '/property-sales'
    | '/rent-collection'
    | '/service-4'
    | '/services'
    | '/terms-of-service'
    | '/blog/$slug'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/about-us'
    | '/career-opportunities'
    | '/consultancy-valuation'
    | '/contact'
    | '/letting-services'
    | '/our-clients'
    | '/our-photo-gallery'
    | '/privacy-policy'
    | '/property-management'
    | '/property-sales'
    | '/rent-collection'
    | '/service-4'
    | '/services'
    | '/terms-of-service'
    | '/blog/$slug'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsRoute: typeof AboutUsRoute
  CareerOpportunitiesRoute: typeof CareerOpportunitiesRoute
  ConsultancyValuationRoute: typeof ConsultancyValuationRoute
  ContactRoute: typeof ContactRoute
  LettingServicesRoute: typeof LettingServicesRoute
  OurClientsRoute: typeof OurClientsRoute
  OurPhotoGalleryRoute: typeof OurPhotoGalleryRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  PropertyManagementRoute: typeof PropertyManagementRoute
  PropertySalesRoute: typeof PropertySalesRoute
  RentCollectionRoute: typeof RentCollectionRoute
  Service4Route: typeof Service4Route
  ServicesRoute: typeof ServicesRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career-opportunities': {
      id: '/career-opportunities'
      path: '/career-opportunities'
      fullPath: '/career-opportunities'
      preLoaderRoute: typeof CareerOpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultancy-valuation': {
      id: '/consultancy-valuation'
      path: '/consultancy-valuation'
      fullPath: '/consultancy-valuation'
      preLoaderRoute: typeof ConsultancyValuationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/letting-services': {
      id: '/letting-services'
      path: '/letting-services'
      fullPath: '/letting-services'
      preLoaderRoute: typeof LettingServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-clients': {
      id: '/our-clients'
      path: '/our-clients'
      fullPath: '/our-clients'
      preLoaderRoute: typeof OurClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-photo-gallery': {
      id: '/our-photo-gallery'
      path: '/our-photo-gallery'
      fullPath: '/our-photo-gallery'
      preLoaderRoute: typeof OurPhotoGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property-management': {
      id: '/property-management'
      path: '/property-management'
      fullPath: '/property-management'
      preLoaderRoute: typeof PropertyManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property-sales': {
      id: '/property-sales'
      path: '/property-sales'
      fullPath: '/property-sales'
      preLoaderRoute: typeof PropertySalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rent-collection': {
      id: '/rent-collection'
      path: '/rent-collection'
      fullPath: '/rent-collection'
      preLoaderRoute: typeof RentCollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-4': {
      id: '/service-4'
      path: '/service-4'
      fullPath: '/service-4'
      preLoaderRoute: typeof Service4RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsRoute: AboutUsRoute,
  CareerOpportunitiesRoute: CareerOpportunitiesRoute,
  ConsultancyValuationRoute: ConsultancyValuationRoute,
  ContactRoute: ContactRoute,
  LettingServicesRoute: LettingServicesRoute,
  OurClientsRoute: OurClientsRoute,
  OurPhotoGalleryRoute: OurPhotoGalleryRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  PropertyManagementRoute: PropertyManagementRoute,
  PropertySalesRoute: PropertySalesRoute,
  RentCollectionRoute: RentCollectionRoute,
  Service4Route: Service4Route,
  ServicesRoute: ServicesRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
